### ISSUE TITLE
ValueError: The length of the provided data is not a multiple of the block length.

### ISSUE THREAD

**Issue by savathuntechquestion** [Dibakarroy1997/kisskh-dl#22]
I've been getting this error midway through trying to download a series. My input is `kisskh dl "https://kisskh.co/Drama/Mysterious-Lotus-Casebook?id=7648" -f 9 --decrypt-subtitle --key "8056483646328763" --initialization-vector "6852612370185273"`

I'm starting at episode 9 because ep 9 is what it fails at

Where I'm using the vektor and decryption key from[ this post](https://github.com/debakarr/kisskh-dl/issues/14#issuecomment-1862055123) since I'm not sure how to generate my own key or vector. 

Full text of the error:
```

C:\Users\username\Downloads>kisskh dl "https://kisskh.co/Drama/Mysterious-Lotus-Casebook?id=7648" -f 9 --decrypt-subtitle --key "8056483646328763" --initialization-vector "6852612370185273"
2024-04-07 16:55:40,336 - INFO - Getting details for Episode 9...
[generic] Extracting URL: https://hls06.videodelivery.shop/hls06/Mysterious-Lotus-Casebook-Ep9/tmp.m3u8
[generic] tmp: Downloading webpage
[generic] tmp: Downloading m3u8 information
[generic] tmp: Checking m3u8 live status
[info] tmp: Downloading 1 format(s): 0
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 690
[download] Destination: C:\Users\username\Downloads\Mysterious_Lotus_Casebook\Mysterious_Lotus_Casebook_E09.mp4
[download] 100% of  362.43MiB in 00:00:05 at 71.44MiB/s
WARNING: tmp: Possible MPEG-TS in MP4 container or malformed AAC timestamps. Install ffmpeg to fix this automatically
2024-04-07 16:55:46,236 - INFO - Downloading English sub...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Scripts\kisskh.exe\__main__.py", line 7, in <module>
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\kisskh_downloader\cli.py", line 132, in dl
    downloader.download_subtitles(subtitles, filepath, decrypter)
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\kisskh_downloader\downloader.py", line 54, in download_subtitles
    decrypted_subtitle = decrypter.decrypt_subtitles(output_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\kisskh_downloader\helper\decrypt_subtitle.py", line 14, in decrypt_subtitles
    decrypted_text = self.cipher.decrypt(sub.text)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\kisskh_downloader\helper\aes_cipher.py", line 19, in decrypt
    decrypted_text = decryptor.update(b64decode(encrypted_text)) + decryptor.finalize()
                                                                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\hazmat\primitives\ciphers\base.py", line 186, in finalize
    data = self._ctx.finalize()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\username\AppData\Local\Programs\Python\Python312\Lib\site-packages\cryptography\hazmat\backends\openssl\ciphers.py", line 222, in finalize
    raise ValueError(
ValueError: The length of the provided data is not a multiple of the block length.
```

**Comment by debakarr** [comment]
Fixed in v0.2.0. The subtitle decryption was updated to use the `cryptography` library with proper AES-CBC PKCS7 unpadding.

Usage:
```
kisskh dl <url> --decrypt-subtitle --key <key> --initialization-vector <iv>
```
