### ISSUE TITLE
403 forbidden error

### ISSUE THREAD

**Issue by maharajgs** [Dibakarroy1997/kisskh-dl#24]
is this blocked? getting an error from yesterday,  raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url

**Comment by lifeon-mars** [comment]
boosting this instead of making my own ticket and adding the traceback i got:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Scripts\kisskh.exe\__main__.py", line 7, in <module>
    sys.exit(kisskh())
             ~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\click\core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\anaconda3\Lib\site-packages\kisskh_downloader\cli.py", line 123, in dl
    video_stream_url = kisskh_api.get_stream_url(episode_id)  # type: ignore
  File "C:\ProgramData\anaconda3\Lib\site-packages\kisskh_downloader\kisskh_api.py", line 120, in get_stream_url
    response = self._request(stream_api_url)
  File "C:\ProgramData\anaconda3\Lib\site-packages\kisskh_downloader\kisskh_api.py", line 67, in _request
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://kisskh.co/api/DramaList/Episode/102551.png?err=false&ts=&time=
```

specifically tried it on a show ive been able to download before with no issue

**Comment by debakarr** [comment]
Fixed in v0.2.0. The 403 error was caused by two things:
1. The site now requires a `kkey` authentication token for stream and subtitle API calls
2. The site domain changed from `kisskh.co` to `kisskh.nl`

Both have been addressed. Update and try:
```
pip install -U kisskh-downloader
```
